### ISSUE TITLE
No registered env with id: VizdoomBasic-v0

### ISSUE THREAD

**Issue by EXJUSTICE** [simontudo/vizdoomgym#3]
Hi,

Not sure if this is maintained any longer, but attempting to run your VizDoomBasic in a online Colaboratory notebook following your tutorial yields the error "No registered env with id: VizdoomBasic-v0"

**Comment by Banjo-000** [comment]
> Hi,
> 
> Not sure if this is maintained any longer, but attempting to run your VizDoomBasic in a online Colaboratory notebook following your tutorial yields the error "No registered env with id: VizdoomBasic-v0"

Not sure if I got exactly the same issue, but if it is, a tactical solution could be to import vizdoomgym after importing gym

`import gym'

'import vizdoomgym`

**Comment by EXJUSTICE** [comment]
Do you mean that the problem lies in the shared gym methods?
Will give it a try.

________________________________

**Comment by shakenes** [comment]
I'm sorry, but I cannot reproduce your error...

**Comment by EXJUSTICE** [comment]
Apologies, just saw this. 
Invoking the following

import gym
import vizdoomgym
env = gym.make('VizdoomBasic-v0')

Results in the error in colaboratory.

No registered env with id: VizdoomBasic-v0

**Comment by shakenes** [comment]
I'm sorry but I'm not able to reproduce your problem with these
informations. Can you please give more information about the collaborative?

Yijie Xu <notifications@github.com> schrieb am Mo., 25. Mai 2020, 22:07:

**Comment by EXJUSTICE** [comment]
Hi Simon,

I've attached the notebook for your reference

https://drive.google.com/open?id=14vws1M3YaQt3RbvrYuu3J6MKtRV4-7lm

I now believe the error is during installation however

"ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /content"

Any tips are welcome.

**Comment by shakenes** [comment]
Thanks for the clarification. I was able to reproduce your error. Please try the following code snippet in Google Colab:
```
!sudo apt-get update
!sudo apt-get install build-essential zlib1g-dev libsdl2-dev libjpeg-dev nasm tar libbz2-dev libgtk2.0-dev cmake git libfluidsynth-dev libgme-dev libopenal-dev timidity libwildmidi-dev unzip

# Boost libraries
!sudo apt-get install libboost-all-dev

# Lua binding dependencies
!apt-get install liblua5.1-dev
!sudo apt-get install cmake libboost-all-dev libgtk2.0-dev libsdl2-dev python-numpy git
!git clone https://github.com/shakenes/vizdoomgym.git
!python3 -m pip install -e vizdoomgym/
```
Then restart your runtime and run
```
import gym
import vizdoomgym
env = gym.make('VizdoomBasic-v0')

# use like a normal Gym environment
state = env.reset()
state, reward, done, info = env.step(env.action_space.sample())
print(state.shape)
# env.render()
env.close()
```

Note that you cannot render the screen output in Colab since there is no screen.

**Comment by EXJUSTICE** [comment]
It does work!
Is it because of the directory information not being updated?

**Comment by shakenes** [comment]
I have no idea... I have almost no experience with Colab and notebooks. But I saw a similar error with a different package which was solved by a restart so I gave it a shot :D

**Comment by EXJUSTICE** [comment]
ahahahhaha what a boss. Thanks mate
