### ISSUE TITLE
step() returns old observation

### ISSUE THREAD

**Issue by techneaponahi** [simontudo/vizdoomgym#5]
I noticed that in the step function the state is recorded before the action is taken. 
Which means that the observation returned is one step old and doesn't correspond to the current state. 
Easy enough to fix by simply putting `self.state = self.game.get_state()`  after `reward = self.game.make_action(act)`.

**Comment by shakenes** [comment]
Fixed in https://github.com/shakenes/vizdoomgym/commit/28770d0bbecefcfd0f2b536326f156b0d16765d1
Thanks for pointing it out!
