### ISSUE TITLE
Error during running

### ISSUE THREAD

**Issue by xuehui1991** [simontudo/vizdoomgym#9]
the code is as follows:

```
import gym
import vizdoomgym

env = gym.make('VizdoomBasic-v0')
```

  File ".../vizdoomgym/vizdoomgym/envs/vizdoomenv.py", line 3, in <module>
    import vizdoom.vizdoom as vzd
ModuleNotFoundError: No module named 'vizdoom'

**Comment by shakenes** [comment]
Is vizdoom installed correctly?
